Repository SV-Winter-BootCamp-TeamD/frontend, pull requests merged in 2024-01, with the labels that each got.

#3 feat: 온보딩 페이지 퍼블리싱
  src/components/OnBoarding/OnBoardingTemplate.tsx
  src/components/OnBoarding/index.tsx
  src/main.tsx
  src/pages/OnBoardingPage.tsx
Labels: 🖼️ Publishing, 💖 Style

#5 Publishing/#1 메인 페이지 퍼블리싱
  src/components/Canvas/Canvas.tsx
  src/components/Canvas/index.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/index.tsx
  src/main.tsx
  src/pages/MainPage.tsx
Labels: 🖼️ Publishing

#7 feat: 회원가입 입력 및 확인
  src/pages/SignUpPage.tsx
Labels: 🖼️ Publishing

#9 Publishing/#8 로그인 페이지 퍼블리싱
  src/pages/LoginPage.tsx
Labels: 🖼️ Publishing, 💖 Style

#14 Feature/#12
  package.json
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  yarn.lock
Labels: 🔧 Feature

#15 Feature/#11
  package.json
  public/images/svg/onBoarding1.svg
  public/images/svg/onBoarding2.svg
  src/components/OnBoarding/OnBoardingTemplate.tsx
  src/pages/OnBoardingPage.tsx
  tailwind.config.js
  yarn.lock
Labels: 🔧 Feature, 💖 Style

#21 Feat/#16 메인 페이지 API 연동
  package.json
  src/components/MainPage/CanvasPreview/CanvasPreview.tsx
  src/pages/MainPage.tsx
  tailwind.config.js
  yarn.lock
Labels: 🔧 Feature

#22 Style/#20 회원가입/로그인 페이지 디자인 수정
  index.html
  src/components/SignupPage/img/background.png
  src/components/SignupPage/img/object.png
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  tailwind.config.js
Labels: 💖 Style

#24 Feat/#19 캔버스 편집 페이지 API 연동
  src/components/CanvasPage/AIBackground/AIBackground.tsx
  src/components/CanvasPage/AIBackgroundGenerator/AIBackgroundGenerator.tsx
  src/components/CanvasPage/AIBackgroundLoading/AIBackgroundLoading.tsx
  src/components/CanvasPage/AISticker/AISticker.tsx
  src/components/CanvasPage/AIStickerGenerator/AIStickerGenerator.tsx
  src/components/CanvasPage/Canvas/Canvas.tsx
  src/components/CanvasPage/History/History.tsx
  src/components/CanvasPage/Invite/Invite.tsx
  src/components/CanvasPage/MenuSection/MenuSection.tsx
  src/components/CanvasPage/MyCanvas/MyCanvas.tsx
  src/components/CanvasPage/NavBar/NavBar.tsx
  src/components/CanvasPage/RecommendBackground/RecommendBackground.tsx
  src/components/CanvasPage/UploadBackground/UploadBackground.tsx
  src/components/CanvasPage/UploadBackground/UploadButton.tsx
  src/components/MainPage/CanvasPreview/CanvasPreview.tsx
  src/pages/CanvasPage.tsx
  src/pages/MainPage.tsx
  tailwind.config.js
Labels: 🔧 Feature

#29 Feat/#28 캔버스 편집 페이지 추가 기능 구현
  src/components/CanvasPage/AIBackground/AIBackground.tsx
  src/components/CanvasPage/AIBackgroundGenerator/AIBackgroundGenerator.tsx
  src/components/CanvasPage/AISticker/AISticker.tsx
  src/components/CanvasPage/Canvas/Canvas.tsx
  src/components/CanvasPage/History/History.tsx
  src/components/CanvasPage/MenuSection/MenuSection.tsx
  src/components/CanvasPage/RecommendBackground/RecommendBackground.tsx
  src/components/CanvasPage/UploadBackground/UploadBackground.tsx
  src/components/CanvasPage/UploadBackground/UploadButton.tsx
  src/index.css
  src/pages/CanvasPage.tsx
Labels: 🔧 Feature

#33 Feature/#27
  src/components/NavBar/NavBar.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: 💖 Style

#36 Feat/#35 yarn build 시 오류 수정
  src/components/MainPage/CanvasPreview/CanvasPreview.tsx
  src/components/NavBar/NavBar.tsx
  src/components/OnBoarding/ThreeTest.tsx
  src/pages/SignUpPage.tsx
Labels: 🛠️ BugFix, 💖 Style

#40 bugfix: object.png 파일 object.svg로 변경
  public/images/svg/object.svg
  src/components/SignupPage/img/object.png
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: 🛠️ BugFix

#42 bugfix: background2.png 경로 수정
  src/components/OnBoarding/ThreeTest.tsx
Labels: 🛠️ BugFix

#45 fix: 오류수정
  package.json
  src/main.tsx
  yarn.lock
Labels: 🛠️ BugFix

#48 Feat/#47 도커 파일 수정
  Dockerfile
Labels: 🔧 Feature

#49 Feat/#34 스켈레톤 UI 구현
  docker-compose.yml
  package.json
  src/api/api.ts
  src/components/CanvasPage/AIBackground/AIBackground.tsx
  src/components/CanvasPage/AIBackgroundLoading/AIBackgroundLoading.tsx
  src/components/CanvasPage/AISticker/AISticker.tsx
  src/components/CanvasPage/AIStickerLoading/AIStickerLoading.tsx
  src/components/CanvasPage/Canvas/Canvas.tsx
  src/components/CanvasPage/Invite/Input.tsx
  src/components/CanvasPage/Invite/Invite.tsx
  src/components/CanvasPage/Invite/MemberList.tsx
  src/components/CanvasPage/MenuBar/MenuBar.tsx
  src/components/CanvasPage/MenuSection/MenuSection.tsx
  src/components/CanvasPage/MyCanvas/MyCanvas.tsx
  src/components/CanvasPage/NavBar/NavBar.tsx
  src/components/CanvasPage/RecommendBackground/RecommendBackground.tsx
  src/components/CanvasPage/RecommendBackgroundLoading/RecommendBackgroundLoading.tsx
  src/components/CanvasPage/RecommendBackgroundLoading/index.tsx
  src/components/CanvasPage/UploadBackground/UploadBackground.tsx
  src/components/General/NavBar/NavBar.tsx
  src/components/General/NavBar/index.tsx
  src/components/General/ReGenerateButton/ReGenerateButton.tsx
  src/components/General/ReGenerateButton/index.tsx
  src/main.tsx
  src/pages/MainPage.tsx
  src/type.ts
  yarn.lock
Labels: 🔧 Feature, 💖 Style

#52 feat:회원가입 로그인 인증 로직 제거
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
Labels: 🔧 Feature

#54 Feat/#50 BASE_URL 변경
  .env
  .gitignore
  index.html
  public/images/svg/download.svg
  public/images/svg/favicon.svg
  src/api/api.ts
  src/components/CanvasPage/AIBackground/AIBackground.tsx
  src/components/CanvasPage/AIBackgroundGenerator/AIBackgroundGenerator.tsx
  src/components/CanvasPage/AIBackgroundGenerator/Color.tsx
  src/components/CanvasPage/AIBackgroundGenerator/Input.tsx
  src/components/CanvasPage/AIBackgroundGenerator/Theme.tsx
  src/components/CanvasPage/AIBackgroundLoading/Loading.tsx
  src/components/CanvasPage/Canvas/Canvas.tsx
  src/components/CanvasPage/History/History.tsx
  src/components/CanvasPage/Invite/Input.tsx
  src/components/CanvasPage/MenuBar/Button.tsx
  src/components/CanvasPage/MenuBar/MenuBar.tsx
  src/components/CanvasPage/MenuSection/MenuSection.tsx
  src/components/CanvasPage/MyCanvas/MyCanvas.tsx
  src/components/CanvasPage/NavBar/NavBar.tsx
  src/components/CanvasPage/RecommendBackground/RecommendBackground.tsx
  src/components/CanvasPage/UploadBackground/UploadBackground.tsx
  src/components/GenearateButton/GenerateButton.tsx
  src/components/MainPage/CanvasPreview/CanvasPreview.tsx
  src/pages/CanvasPage.tsx
  src/pages/MainPage.tsx
Labels: 🔧 Feature

#56 Feat/#53 페이지 전환 방식 수정
  src/components/General/NavBar/NavBar.tsx
  src/components/MainPage/CanvasPreview/CanvasPreview.tsx
  src/components/OnBoarding/OnBoardingTemplate.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignUpPage.tsx
Labels: 🔧 Feature

#59 Style/#57 기본 폰트로 수정
  src/components/General/NavBar/NavBar.tsx
  src/components/General/NavBar/index.tsx
  src/components/OnBoarding/OnBoardingTemplate.tsx
  src/pages/MainPage.tsx
  src/pages/OnBoardingPage.tsx
  src/pages/SideBar.tsx
Labels: 💖 Style

#61 Style/#60 온보딩 페이지 코드 리팩토링 및 홈으로 기능 구현
  src/components/CanvasPage/NavBar/NavBar.tsx
  src/components/OnBoarding/ImageSlider.tsx
  src/components/OnBoarding/LottiePlayer.tsx
  src/components/OnBoarding/OnBoardingTemplate.tsx
  src/components/OnBoarding/PathDrawing.tsx
  src/pages/MainPage.tsx
Labels: 🔧 Feature, 🪄 Refactoring, 💖 Style

#64 Style/#55 캔버스 편집 페이지 디자인 수정
  .env
  public/images/svg/download.svg
  src/components/CanvasPage/Canvas/Canvas.tsx
  src/components/CanvasPage/Invite/Input.tsx
  src/components/CanvasPage/MenuBar/MenuBar.tsx
  src/components/CanvasPage/NavBar/NavBar.tsx
  src/components/CanvasPage/UploadBackground/UploadButton.tsx
  src/pages/CanvasPage.tsx
Labels: 💖 Style
